Gazebo urdf improvements
swri-robotics/collaborative-robotic-sanding pull request #34
Opened 2020-02-19 19:54 UTC by jrgnicho

This PR uses a xacro to create urdf files for gazebo and for previewing motion
It also creates a soft link into the .gazebo/models directory so that gazebo can find the robot mesh resources

2020-02-20 13:54 UTC, mpowelson commented
While I understand why you added it, I don't think rosdep will actually pull libompl-dev since there is no key for it. Personally I am fine with leaving it in the package.xml to make people aware of what they need to install, but I don't know if that is best practice. If you do, you'll need to add it to the travis.yaml ROSDEP_SKIP_KEYS in order for CI to pass.

2020-02-20 16:14 UTC, marrts commented on crs_support/launch/environment_launch.launch.py
> +        for cmd, req_ in cmd_dict.items():
The try-except should be inside the for loop. The way it is currently set up is if the cmd4 fails, which it often does if gazebo isn't running, then it won't even try cmd1.

2020-02-20 16:17 UTC, marrts requested changes
Looks good, much better way of making sure the gazebo models directory is populated and the preview joint_state now works smoothly with the regular joint_state. Only change is that the link between crs_support and .gazebo/models doesn't always work as currently implemented.

2020-02-21 19:43 UTC, jrgnicho commented
@mpowelson  is the ROSDEP_SKIP_KEYS a new file that I'd have to create in the repo?

2020-02-21 19:51 UTC, jrgnicho commented
> Looks good, much better way of making sure the gazebo models directory is populated and the preview joint_state now works smoothly with the regular joint_state. Only change is that the link between crs_support and .gazebo/models doesn't always work as currently implemented.

I haven't had the `ln -s ...` command fail on me yet.  Does it not create the link?

2020-02-21 20:47 UTC, merged