Removed redudant tesseractRosUtilsToMsg usage
swri-robotics/collaborative-robotic-sanding pull request #50
Opened 2020-03-20 22:10 UTC by marrts

Resolves #49

2020-03-21 16:56 UTC, mpowelson requested changes
Looks good. You'll need to run clang formatting. Also, if you can remove the tesseract dependency that would greatly be preferred.

2020-03-21 16:56 UTC, mpowelson commented on crs_motion_planning/include/crs_motion_planning/path_processing_utils.h
> -
I think you can get rid of line 22 now. I think this is the only one that depends on tesseract
```
#include <tesseract_common/types.h>
```

2020-03-21 16:56 UTC, mpowelson commented on crs_motion_planning/src/path_processing_utils.cpp
> -void crs_motion_planning::tesseractRosutilsToMsg(trajectory_msgs::msg::JointTrajectory& traj_msg,
It looks like you don't need tesseract here either anymore. You should be able to remove `  tesseract::tesseract_common` from the target_link_libraries

2020-03-23 14:11 UTC, mpowelson approved these changes

2020-03-23 14:11 UTC, mpowelson commented
When CI passes we can merge.

2020-03-23 15:12 UTC, mpowelson commented
I'm not sure why this failed.

2020-03-23 15:15 UTC, marrts commented
I was afraid this might happen, something to do with the tesseract linked library in path_processing_utils. It also failed on my machine on my first attempt to build crs_gui.

2020-03-23 15:16 UTC, mpowelson commented
Do you want me to look into this?

2020-03-23 15:22 UTC, marrts commented
Yeah, I think it has to do with crs_gui dependencies, so you'd probably be better equipped to look into it. I also found it odd that I had to add iterative_spline_parameterization to the crs_gui CMakeLists since it shouldn't need to use that anywhere, maybe these two issues are related.

2020-03-23 15:24 UTC, mpowelson commented
Yeah that doesn't sound good. We must have some CMake gremlins.

2020-03-23 17:57 UTC, mpowelson commented
I pushed some changes that will let it build at this point. Jorge has some more fixes in his PR that cleans up a few other things, but hopefully this will pass.

2020-03-23 19:50 UTC, marrts commented
Seems like this should be good to merge unless there are any objections

2020-03-23 20:19 UTC, merged