WIP: Wsu integration testing
swri-robotics/collaborative-robotic-sanding pull request #85
Opened 2020-08-13 22:58 UTC by marrts

Various changes made during integration process at WSU

2020-08-13 23:00 UTC, marrts commented
This likely should not be merged as is. There are current changes to the path loader in path_processing_utils.cpp that were made for the sake of getting better toolpaths for testing. This change should be reverted and better toolpaths be specifically made that don't have to be altered in the loading process.

2020-08-21 16:15 UTC, jrgnicho reviewed
It seems some commits from the integration branch are in this PR, can you rebase?  I can resume reviewing after that

2020-08-21 16:15 UTC, jrgnicho commented on crs_application/config/main/motion_planning/MP_config.yaml
> +  use_trajopt_surface: true
Is the planning time significantly increased with these options on?

2020-08-21 16:15 UTC, jrgnicho commented on crs_application/config/main/motion_planning/MP_config.yaml
> +  additional_tool_offset: [0.0, 0.0, 0.004, 0.0, 0.0, 0.0]
Is this offset used to account for the sanding disk padding?

2020-08-21 16:15 UTC, jrgnicho commented on crs_application/config/main/motion_planning/MP_config.yaml
> +  smooth_accelerations: true
What is the computational impact of enabling these options on motion planning?

2020-08-21 16:25 UTC, marrts commented on crs_application/config/main/motion_planning/MP_config.yaml
> +  use_trajopt_surface: true
It is increased but not significantly due to the parts low mesh resolution. The freespace one allows for more control on keeping the robot further away from the part during freespace motions which is nice, and the surface one allows for smoother motions on the surface with smaller rotation around the z-axis of the sander. Additionally the surface on allows for collisions between the sander and the part so we don't have to count on an offset from descartes and can actually plan directly on the surface.

2020-08-21 16:26 UTC, marrts commented on crs_application/config/main/motion_planning/MP_config.yaml
> +  additional_tool_offset: [0.0, 0.0, 0.004, 0.0, 0.0, 0.0]
This offset is so that descartes can plan without collisions being detected. Without this all points would be deemed unreachable. Trajopt then optimizes them directly onto the surface. Smaller is better, but too small and it completely fails

2020-08-21 16:27 UTC, marrts commented on crs_application/config/main/motion_planning/MP_config.yaml
> +  smooth_accelerations: true
Doesn't seem to have a noticeable computational impact, but gives better results and prevents sharp changes in rotation of the end effector, which is very desirable.

2020-08-21 16:28 UTC, marrts commented
Done rebasing

2020-08-22 17:08 UTC, jrgnicho requested changes

2020-08-22 17:08 UTC, jrgnicho commented on crs_application/config/toolpath_crop/region_detection_opencv_split_imgs.yaml
> +  mode: 0
This file is no longer used, please delete

2020-08-22 17:08 UTC, jrgnicho commented on crs_application/config/swri/part_localization.yaml
> +    size: [2.0, 2.0, 0.9]
I don't see why this had to change since this is the config for the surrogate workcell

2020-08-22 17:08 UTC, jrgnicho commented on crs_application/src/task_managers/process_execution_manager.cpp
> +    std::chrono::duration<double> sleep_dur(WAIT_ROBOT_STOP);
Why is the pause needed?

2020-08-22 17:08 UTC, jrgnicho commented on crs_motion_planning/src/motion_planning_server.cpp
> +static const std::string MOTION_PLANNING_CONFIG_PATH = "config/motion_planning/MP_config.yaml";
It shouldn't be necessary to hardcode the path to the config file since it is already passed as an argument, see [here ](https://github.com/swri-robotics/collaborative-robotic-sanding/blob/72bf6fe8ac9fef8ed347ef844056944f9cfdd09c/crs_support/launch/environment_launch.launch.py#L183)

2020-08-22 17:08 UTC, jrgnicho commented on crs_motion_planning/src/path_processing_utils.cpp
> +      if ((first_xyz - prev_end).norm() < (last_xyz - prev_end).norm())
What does this do?
Regardless, it seems that this could be done in a separate function after it has been parsed

2020-08-22 17:08 UTC, jrgnicho commented on crs_motion_planning/src/path_processing_utils.cpp
> +    if (req_joint_vel > max_vel_adj || dist_traveled > max_dist || abs(given_traj.points[i].positions[4]) < 0.03)
Not a fan of hardcoded values, furthermore this check feels very specific to the main workcell

2020-08-22 17:08 UTC, jrgnicho commented on crs_motion_planning/src/path_processing_utils.cpp
> +  cartesian_trajectory.points.back().wrench.force.z = 0;
Was this wrench value ever used?

2020-08-22 17:08 UTC, jrgnicho commented on crs_process_data/data/main/toolpaths/part_2/configs/job_0_degrees_20200520T192241.997282_config.yaml
> +  part_rework: {}
Was this accidentally added? It looks like an old version of the config file since it is missing the rework section

2020-08-22 17:08 UTC, jrgnicho commented on crs_process_data/data/surrogate1/toolpaths/part_2/configs/job_0_degrees_20200520T192241.997282_config.yaml
> +  part_rework: {}
Same as above

2020-08-22 17:08 UTC, jrgnicho commented on crs_support/urdf/crs.urdf.xacro
> +        <origin rpy="0 0 3.14" xyz="0 0 0" />-->
so the physical robot's base was rotated 180 degrees?

2020-08-22 17:08 UTC, jrgnicho commented on crs_support/urdf/crs.urdf.xacro
> +                <mesh filename="package://crs_support/meshes/end_effector/visual/flipped_tool.stl" />
If this is the new tool then we should rename it and delete the old one

2020-08-22 17:08 UTC, jrgnicho commented on crs_support/urdf/crs.urdf.xacro
> +                <mesh filename="package://crs_support/meshes/end_effector/collision/flipped_tool_collision.stl" />
Same as above

2020-08-22 17:08 UTC, jrgnicho commented on crs_support/urdf/crs.urdf.xacro
> +                <mesh filename="package://crs_support/meshes/end_effector/collision/flipped_sander_collision.stl" />
Same as above

2020-08-22 17:08 UTC, jrgnicho commented on crs_support/urdf/crs.urdf.xacro
> +          <origin rpy="0 1.57 0" xyz="0.0 -0.2 -.0375" />
What are all of these cylinders?

2020-08-22 18:28 UTC, marrts commented on crs_application/config/toolpath_crop/region_detection_opencv_split_imgs.yaml
> +  mode: 0
Removed

2020-08-22 18:28 UTC, marrts commented on crs_application/config/swri/part_localization.yaml
> +    size: [2.0, 2.0, 0.9]
Reverted

2020-08-22 18:29 UTC, marrts commented on crs_application/src/task_managers/process_execution_manager.cpp
> +    std::chrono::duration<double> sleep_dur(WAIT_ROBOT_STOP);
So that the robot can wait for any bouncing to stop before the force torque sensor is zeroed, this is important.

2020-08-22 18:29 UTC, marrts commented on crs_motion_planning/src/motion_planning_server.cpp
> +static const std::string MOTION_PLANNING_CONFIG_PATH = "config/motion_planning/MP_config.yaml";
Removed

2020-08-22 18:31 UTC, marrts commented on crs_motion_planning/src/path_processing_utils.cpp
> +      if ((first_xyz - prev_end).norm() < (last_xyz - prev_end).norm())
This makes sure the rasters alternate back and forth. The generated rasters were out of order so I had to manually adjust their order, and then they no longer went back and forth and rather than manually adjusting that as well I put in this check. I agree that it would like be better to just add a later path processor that both correctly orders the paths and correctly orients them.

I can do this when I implement the sphere of reachability we discussed. For now I think it would be best to keep this since it doesn't break anything.

2020-08-22 18:32 UTC, marrts commented on crs_motion_planning/src/path_processing_utils.cpp
> +    if (req_joint_vel > max_vel_adj || dist_traveled > max_dist || abs(given_traj.points[i].positions[4]) < 0.03)
Removed and reimplemented check for wrist 2 joint value in the descartes stage. This is not specific to the main workcell, it is specific to UR's to avoid wrist singularities which occur at wrist 2 joint values of zero.

2020-08-22 18:33 UTC, marrts commented on crs_motion_planning/src/path_processing_utils.cpp
> +  cartesian_trajectory.points.back().wrench.force.z = 0;
This is the last given wrench target value for the force controller and it is used. I determined that a target of zero was better than the negative force.

2020-08-22 18:33 UTC, marrts commented on crs_process_data/data/main/toolpaths/part_2/configs/job_0_degrees_20200520T192241.997282_config.yaml
> +  part_rework: {}
removed

2020-08-22 18:33 UTC, marrts commented on crs_process_data/data/surrogate1/toolpaths/part_2/configs/job_0_degrees_20200520T192241.997282_config.yaml
> +  part_rework: {}
removed

2020-08-22 18:35 UTC, marrts commented on crs_support/urdf/crs.urdf.xacro
> +        <origin rpy="0 0 3.14" xyz="0 0 0" />-->
Kinda, I actually rotated both the base to base_link and the world to base by 180 degrees. The reason being was the tcp frame on the UR controller was 180 degrees around the base of the robot. This caused issues because the UR driver gives the wrench in the tcp frame set on the UR teach pendant, and it wasn't match to where it was showing in our ROS environment. This change here fixed that issue but resulted in a net zero change to the simulation.

2020-08-22 18:36 UTC, marrts commented on crs_support/urdf/crs.urdf.xacro
> +                <mesh filename="package://crs_support/meshes/end_effector/visual/flipped_tool.stl" />
Renamed and removed old ones, also updated swri urdf to match

2020-08-22 18:36 UTC, marrts commented on crs_support/urdf/crs.urdf.xacro
> +                <mesh filename="package://crs_support/meshes/end_effector/collision/flipped_tool_collision.stl" />
same as above

2020-08-22 18:37 UTC, marrts commented on crs_support/urdf/crs.urdf.xacro
> +          <origin rpy="0 1.57 0" xyz="0.0 -0.2 -.0375" />
These are for the vacuums and hoses connected to the end effector which aren't fully accounted for in the stl file we have. These help a lot for better motion planning.

2020-08-22 19:19 UTC, jrgnicho commented on crs_motion_planning/src/path_processing_utils.cpp
> +      if ((first_xyz - prev_end).norm() < (last_xyz - prev_end).norm())
Sounds good, make sure to create an issue if there isn't one for it yet

2020-08-22 19:25 UTC, jrgnicho commented on crs_motion_planning/src/path_planning_utils.cpp
> +      std::make_shared<ur_ikfast_kinematics::UR10eKinematicsD>(world_to_base_link, tool0_to_sander, isValidFn, nullptr);
Is there anyway to make this unspecific to the UR10 or at least have the option to skip this if the UR10 wasn't used?

2020-08-22 19:29 UTC, jrgnicho commented on crs_motion_planning/src/path_processing_utils.cpp
> +  cartesian_trajectory.points.back().wrench.force.z = 0;
if target_wrench  is read from a config file could the value of 0 not be set there instead?

2020-08-22 19:46 UTC, marrts commented on crs_motion_planning/src/path_planning_utils.cpp
> +      std::make_shared<ur_ikfast_kinematics::UR10eKinematicsD>(world_to_base_link, tool0_to_sander, isValidFn, nullptr);
It's already using specifically the ur ikfast, so that would be a bigger undertaking itself.

2020-08-22 19:47 UTC, marrts commented on crs_motion_planning/src/path_processing_utils.cpp
> +  cartesian_trajectory.points.back().wrench.force.z = 0;
This is specifically the last waypoint is set to zero, every other waypoint is set by the target force config variable.

2020-08-24 14:56 UTC, jrgnicho commented on crs_motion_planning/src/path_planning_utils.cpp
> +      std::make_shared<ur_ikfast_kinematics::UR10eKinematicsD>(world_to_base_link, tool0_to_sander, isValidFn, nullptr);
OK, I'll create an issue so that at least we are aware of it

2020-08-24 14:57 UTC, merged